# config/routes.yaml

accueil:
    path: /
    controller: App\Controller\AccueilController::index

videos:
    path: /videos
    controller: App\Controller\VideoController::index

chaine:
    path: /chaine/{id}
    controller: App\Controller\ChaineController::index

recherche:
    path: /recherche
    controller: App\Controller\RechercheController::index

chaine_ajouter:
    path: /chaine/ajouter
    controller: App\Controller\ChaineController::ajouter

chaine_editer:
    path: /chaine/editer/{id}
    controller: App\Controller\ChaineController::editer

